# Statistics Exercises

In [98]:
import numpy as np
import pandas as pd

### 1. How likely is it that you roll doubles when rolling two dice?

In [101]:
#Represent the data
outcomes = [1, 2, 3, 4, 5, 6]

#create a matrix of random data
number_of_simulations = 100_000
n_trials = 2

#apply an aggregate function row wise
dice_one_roll = np.random.choice(outcomes, size=number_of_simulations)
dice_two_roll = np.random.choice(outcomes, size=number_of_simulations)
(dice_one_roll == dice_two_roll).mean()

0.16576

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [3]:
outcomes = [1 , 0]
number_of_simulations = 100_000
n_trials = 8

flips = np.random.choice(outcomes, size=(number_of_simulations, n_trials))
flips
sum_of_flips = flips.sum(axis=1)

In [108]:
probability_for_3_heads = (sum_of_flips == 3).mean()
print(f"The probability for getting exactly 3 heads when flipping 8 coins is: {probability_for_3_heads}")

The probability for getting exactly 3 heads when flipping 8 coins is: 0.21689


In [110]:
probability_for_more_than_3_heads = (sum_of_flips >= 3).mean()

print(f"The probability for getting more than 3 heads when flipping 8 coins is: {probability_for_more_than_3_heads}")

The probability for getting more than 3 heads when flipping 8 coins is: 0.85519


### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [111]:
outcomes = [0, 1]
number_of_simulations = 10_000
n_trials = 2

billboard = np.random.choice(outcomes, size=(number_of_simulations,n_trials), p=[.75, .25])
sum_of_billboard = billboard.sum(axis=1)
(sum_of_billboard == 2).mean()

0.0631

### 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [115]:
pop_consumption = np.random.normal(3, 1.5, size=(100_000, 5))
poptart_qty_on_fri =  (pop_consumption.sum(axis=1))
(poptart_qty_on_fri >= 17).mean()


0.27405

### 5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- If a man and woman are chosen at random, P(woman taller than man)?

In [118]:
male_height = np.random.normal(178, 8, 100_000)
female_height = np.random.normal(170, 6, 100_000)
probability_for_taller_female = (female_height > male_height).mean()
probability_for_taller_female

0.21234

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?



In [22]:
#outcomes = ["success", "fail"]
outcomes = [0, 1]

#The probability of success is 1/250 or .996 which leaves the probability for failure as .004...I'll use these as bias for the outcomes
anaconda_install_problems_50 = np.random.choice(outcomes, size=(100_000, 50), p=[.996, .004])
anaconda_install_problems_50

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [36]:
no_install_failures_50 = (anaconda_install_problems_50.sum(axis=1) == 0).mean()
print(f"The probability that none of the first 50 students exerpeince an install failure is: {no_install_failures_50}")

The probability that none of the first 50 students exerpeince an install failure is: 0.81624


In [25]:
anaconda_install_problems_100 = np.random.choice(outcomes, size=(100_000, 100), p=[.996, .004])
anaconda_install_problems_100

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [42]:
no_install_failures_100 = (anaconda_install_problems_100.sum(axis=1) == 0).mean()
print(f"The probability that none of the first 100 students exerpeince an install failure is: {no_install_failures_100}")

The probability that none of the first 100 students exerpeince an install failure is: 0.67006


- **What is the probability that we observe an installation issue within the first 150 students that download anaconda?**

In [43]:
install_failure_150 = np.random.choice(outcomes, size=(100_000, 150), p=[.996, .004])
(install_failure_150.sum(axis=1) > 0).mean()

0.45307

- **How likely is it that 450 students all download anaconda without an issue?**

In [45]:
no_install_problems_450 = np.random.choice(outcomes, size=(100_000, 450), p=[.996, .004])
(no_install_problems_450.sum(axis=1) == 0).mean()

0.16665

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?



In [133]:
#outcomes = ["food", "no_food"]
outcomes = [0, 1]
no_foodtruck_probability = np.random.choice(outcomes, size=(100_000, 3), p=[.70,.30])
(no_foodtruck_probability.sum(axis=1) == 3).mean()

0.02616

- **How likely is it that a food truck will show up sometime this week?**

In [134]:
#I set the trials to 4 because out of a 7 day week where a food truck has not showed up for the first three days, leaves 4 days remaining
foodtruck_this_week = np.random.choice(outcomes, size=(100_000, 4), p=[.70,.30])
(foodtruck_this_week.sum(axis=1) > 0).mean()

0.75714

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [139]:
outcomes = range(0, 365)
n_simulations = 100_000
n_trials = 23

room = np.random.choice(outcomes, size=(n_simulations, n_trials))
room

array([[176,  92,  48, ..., 215, 126,  80],
       [352, 160,  75, ..., 278, 203, 145],
       [108, 147,  63, ..., 142, 261, 236],
       ...,
       [299, 304, 236, ..., 277, 300, 186],
       [159, 269, 127, ..., 234, 236,   0],
       [300,  20, 155, ...,   9,  26, 181]])

In [166]:
lst_doubles = [len(np.unique(room[n])) for n in range(0, n_simulations-1) if len(np.unique(room[n])) <= 1]
lst_doubles

[]

In [162]:
prop_doubles = len(lst_doubles) / n_simulations
prop_doubles

0.0